doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geometry:   LongitudeOne\Spatial\DBAL\Types\GeometryType
            point:      LongitudeOne\Spatial\DBAL\Types\Geometry\PointType
            polygon:    LongitudeOne\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: LongitudeOne\Spatial\DBAL\Types\Geometry\LineStringType
            multipolygon: LongitudeOne\Spatial\DBAL\Types\Geometry\MultiPolygonType
        mapping_types:
            _text: string
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            numeric_functions:
                power: Zogs\UtilsBundle\DQL\Power
                asin: Zogs\UtilsBundle\DQL\Asin
                sin: Zogs\UtilsBundle\DQL\Sin
                pi : Zogs\UtilsBundle\DQL\Pi
                cos: Zogs\UtilsBundle\DQL\Cos
            datetime_functions:
                DAYNAME: Zogs\UtilsBundle\DQL\Dayname
                DAY: Zogs\UtilsBundle\DQL\Day
                MONTH: Zogs\UtilsBundle\DQL\Month
                YEAR: Zogs\UtilsBundle\DQL\Year
                DATE: Zogs\UtilsBundle\DQL\Date
